int mytest_GetR(int x, int y);
int mytest_ri(int x, int y);
double mytest_rd(int x, int y, int z);
int * mytest_rfr(int numWidth, int denomWidth);
int mytest_is_prime(int x);
int * mytest_prime_factors(int x, int *ptr, int * element_count);
long long mytest_lcm(int * set);
int mytest_hcf(int * set);
int mytest_otherhcf(int * set);
int mytest_get_max_prime();
char * mytest_boolOut(int b, char * rtn);
void mytest_swap(int * x, int * y);
int mytest_strlen_int(int x);
int mytest_strlen_double(double x);
int gjlib_sq(int x, int y);
int gjlib_notSq(int x, int y);
int gjlib_isInt(double x);
int gjlib_isSquare(int x);
int gjlib_int_choose(int * rtn);
double gjlib_shrink(double x, int power);
int gjlib_int_not( int notMe, int x, int y, int (*func)(int, int));
double gjlib_significant_figures(double num, int figures);
char * mytest_to_super(char * str, char * rtn);
char * mytest_to_sub(char * str, char * rtn);
char * mytest_to_standard_form(double num, char * rtn);